services:
  frontend:
    build:
      context: ./cloud-storage-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./cloud-storage-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ${VOLUME_PATH?VOLUME_PATH is required as it is the path of the directory that will be mounted in the container}:/root/fs